version: '3.8'

services:
  httpd:
    image: httpd:latest
    container_name: site-portifolio
    ports:
      - "80:80"
    volumes:
      - /site/www/site/:/usr/local/apache2/htdocs/
    restart: always

